### ISSUE TITLE
Codecepticon hangs when obfuscating projects that contain stupidly large byte arrays 

### ISSUE THREAD

**Issue by su1s** [Accenture/Codecepticon#2]
Back again ! 
As per title project that works fine with Codecepticon with normal size payload byte arrays appears to hang when large byte arrays are included, E.G

```
public static byte[] cs = new byte[5885888] { 
	0x80, 0x16, 0xdc, 0x46, 0x26, 0x11, 0xaf, 0x69, 0x9d, 0x04, 0x2a, 0x0c, 0x88, 0x8e, 0xeb, 0xe1, 0xb0, 0x28, 0x13, 0x95, 0x67, 0x53, 
	0xa3, 0xd8, 0x69, 0x79, 0x31, 0xf1, 0xdd, 0x74, 0xe7, 0x58, 0x04, 0xeb, 0xbf, 0x07, 0x0d, 0xbf, 0x98, 0x0c, 0xd0, 0xf3, 0xa8, 0x8c, 
	0xbc, 0xf6, 0x4a, 0x64, 0x57, 0xec, 0x35, 0xf0, 0xba, 0xa9, 0xf3, 0x01, 0x08, 0x60, 0x9b, 0x57, 0xca, 0x11, 0x56, 0xc3, 0xfd, 0xc9, 
```
(Don't ask!! )

Hangs at 

`[14:26:19] Renaming 10 classes...`

**Comment by sadreck** [comment]
"Go big or go home" right?

That is weird indeed as Codecepticon wouldn't mess with the value of the byte array no matter the size.

I'll have a look to see why it's taking that long.

**Comment by su1s** [comment]
Thanks, yeah seems odd, I've not attempted to work out whats going on tbh ... command line in case it helps is 

`Codecepticon.exe --action obfuscate --module csharp --verbose --path "Z:\folder\Temp\Runner\Runner\Runner.sln" --map-file "Z:\folder\Temp\Runner\CodeCeption\mapping.html" --precompile --build --build-path "Z:\folder\Temp\Runner\CodeCeption" --rename ncefpav --rename-method markov --markov-min-length 5 --markov-max-length 12 --markov-min-words 1 --markov-max-words 4 --string-rewrite --string-rewrite-method xor`

**Comment by su1s** [comment]
![image](https://user-images.githubusercontent.com/1630405/211044047-bbc8070d-fb38-4e1d-a434-6740aa68b4a0.png)

I'll let you know if it finishes by the end of the day

**Comment by su1s** [comment]
Feel like I'm spamming this thread now, it does eventually get there, similar delay in renaming variables if it helps 
![image](https://user-images.githubusercontent.com/1630405/211060551-6b5f98eb-d96e-4c77-842a-18273d67f947.png)

**Comment by sadreck** [comment]
I've had a look at this and created a random array of the same size of `5885888`.

Unfortunately the delay happens when Roslyn is actually renaming/analysing something - so it's not a loop or something that I created. I looked into any configuration options (when initialising the workspace) that could speed this up, but I didn't find anything useful. 

I haven't tested this with any other version of Roslyn other than v3.9, as the future ones stil have this bug here https://github.com/dotnet/roslyn/issues/58463 - you could give it a go and see what happens? But if you upgrade that version, other obfuscation targets may fail (I think it was Rubeus that was breaking).

Having said that, I think the only "viable" option would be to obfuscate without the value of that byte array, then inject the byte array by either manually pasting or scripting it, and then compile using VS.

But if you manage to find any configuration that would speed this up, please let me know and I'll include it in the docs (or implemented if it can be set when creating the workspace).

**Comment by su1s** [comment]
Just to follow up on this one. Managed to get around to testing this in a later version of Roslyn today. 
Bumped Codecepticon to 1.1 and Roslyn to 4.5 (Current stable), project is a touch bigger over all but using the same size large byte array.
In short 4.5 appears to be worse/slower over all and runs out of memory without completing 

![image](https://user-images.githubusercontent.com/1630405/221934835-959397db-0ce3-482c-93eb-35c28f0ff844.png)

Running the same thing (1.1 with Roslyn 4.5) works in approx. 3 minutes with out the large bytearray just for reference. 

As mentioned isn't a big issue for me to script the bytearray in later so just going that way for now.  Thanks again for looking into it (Y)

**Comment by sadreck** [comment]
Thanks for the update, in that case I'll close this issue.
